const creatures = [
    {
        id: 1,
        name: "Demon",
        imgPath: "img/creature/demon_creature.png",
        price: 50,
        hp: 60,
        attack: 50,
        attackName: "Slash",
        attackType: "Normal",
        speed: 60,
        defense: 20,
        critical: 25,
        mp: 100,
        mpRegen: 25,
        special: 75,
        specialCost: 100,
        specialName: "Harvest",
        specialType: "Lifesteal",
        specialEffect: "special_effect1"
    },
    {
        id: 2,
        name: "Medusa",
        imgPath: "img/creature/medusa_creature.png",
        price: 50,
        hp: 110,
        attack: 30,
        attackName: "Gaze",
        attackType: "Magic",
        speed: 30,
        defense: 15,
        critical: 15,
        mp: 100,
        mpRegen: 25,
        special: 75,
        specialCost: 100,
        specialName: "Petrify",
        specialType: "Magic",
        specialEffect: "special_effect2"
    },
    {
        id: 3,
        name: "Baby Dragon",
        imgPath: "img/creature/small_dragon_creature.png",
        price: 50,
        hp: 60,
        attack: 50,
        attackName: "Exhale",
        attackType: "Magic",
        speed: 60,
        defense: 20,
        critical: 25,
        mp: 100,
        mpRegen: 25,
        special: 75,
        specialCost: 100,
        specialName: "Fireball",
        specialType: "Magic",
        specialEffect: "special_effect3"
    },
    {
        id: 4,
        name: "Lizard",
        imgPath: "img/creature/lizard_creature.png",
        price: 50,
        hp: 110,
        attack: 30,
        attackName: "Impale",
        attackType: "Normal",
        speed: 30,
        defense: 15,
        critical: 15,
        mp: 100,
        mpRegen: 25,
        special: 75,
        specialCost: 100,
        specialName: "Inject",
        specialType: "Poison",
        specialEffect: "special_effect4"
    },
    {
        id: 5,
        name: "Ice Golem",
        imgPath: "img/creature/ice_golem_creature.png",
        price: 50,
        hp: 110,
        attack: 30,
        attackName: "Slice",
        attackType: "Magic",
        speed: 30,
        defense: 15,
        critical: 15,
        mp: 100,
        mpRegen: 25,
        special: 75,
        specialCost: 100,
        specialName: "Ice Cloak",
        specialType: "Heal",
        specialEffect: "special_effect5"
    },
    {
        id: 6,
        name: "Nuclear Golem",
        imgPath: "img/creature/nuke_golem_creature.png",
        price: 500,
        hp: 60,
        attack: 50,
        attackName: "Slice",
        attackType: "Magic",
        speed: 60,
        defense: 20,
        critical: 25,
        mp: 100,
        mpRegen: 25,
        special: 37.5,
        specialCost: 50,
        specialName: "Rad Cloak",
        specialType: "Lifesteal",
        specialEffect: "special_effect6"
    },
    {
        id: 7,
        name: "Quantum Golem",
        imgPath: "img/creature/quantum_golem_creature.png",
        price: 500,
        hp: 60,
        attack: 50,
        attackName: "Slice",
        attackType: "Magic",
        speed: 60,
        defense: 20,
        critical: 25,
        mp: 100,
        mpRegen: 25,
        special: 37.5,
        specialCost: 50,
        specialName: "Electro Cloak",
        specialType: "Heal",
        specialEffect: "special_effect7"
    }
];

export default creatures;