const creatures = [
    {
        id: 1,
        name: "Demon",
        imgPath: "img/creature/demon_creature.png",
        price: 50,
        hp: 60,
        attack: 50,
        attackName: "Slash",
        attackType: "Normal",
        speed: 60,
        defense: 20,
        critical: 25,
        mp: 100,
        mpRegen: 25,
        special: 75,
        specialCost: 100,
        specialName: "Harvest",
        specialType: "Poison",
        specialEffect: "special_effect1"
    },
    {
        id: 2,
        name: "Medusa",
        imgPath: "img/creature/medusa_creature.png",
        price: 50,
        hp: 110,
        attack: 30,
        attackName: "Gaze",
        attackType: "Magic",
        speed: 30,
        defense: 15,
        critical: 15,
        mp: 100,
        mpRegen: 25,
        special: 75,
        specialCost: 100,
        specialName: "Petrify",
        specialType: "Magic",
        specialEffect: "special_effect2"
    },
    {
        id: 3,
        name: "Baby Dragon",
        imgPath: "img/creature/small_dragon_creature.png",
        price: 50,
        hp: 60,
        attack: 50,
        attackName: "Exhale",
        attackType: "Magic",
        speed: 60,
        defense: 20,
        critical: 25,
        mp: 100,
        mpRegen: 25,
        special: 75,
        specialCost: 100,
        specialName: "Fireball",
        specialType: "Magic",
        specialEffect: "special_effect3"
    },
    {
        id: 4,
        name: "Lizard",
        imgPath: "img/creature/lizard_creature.png",
        price: 50,
        hp: 110,
        attack: 30,
        attackName: "Impale",
        attackType: "Normal",
        speed: 30,
        defense: 15,
        critical: 15,
        mp: 100,
        mpRegen: 25,
        special: 75,
        specialCost: 100,
        specialName: "Poison",
        specialType: "Poison",
        specialEffect: "special_effect4"
    }
];

export default creatures;