export const enemyCreaturesHome = [
  {
    id: 1,
    name: "Demon",
    imgPath: "img/creature/demon_creature.png",
    reward: 3,
    hp: 60,
    attack: 50,
    attackType: "Normal",
    speed: 60,
    defense: 20,
    critical: 25,
  },
  {
    id: 2,
    name: "Lizard",
    imgPath: "img/creature/lizard_creature.png",
    reward: 3,
    hp: 110,
    attack: 30,
    attackType: "Normal",
    speed: 30,
    defense: 15,
    critical: 15,
  },
];

export const enemyCreaturesStage1 = [
  {
    id: 1,
    name: "Medusa",
    imgPath: "img/creature/medusa_creature.png",
    reward: 5,
    hp: 110,
    attack: 30,
    attackType: "Magic",
    speed: 30,
    defense: 15,
    critical: 15,
  },
  {
    id: 2,
    name: "Baby Dragon",
    imgPath: "img/creature/small_dragon_creature.png",
    reward: 5,
    hp: 60,
    attack: 50,
    attackType: "Magic",
    speed: 60,
    defense: 20,
    critical: 25,
  },
];

export const enemyCreaturesStage2 = [
  {
    id: 1,
    name: "Skeleton",
    imgPath: "img/creature/skeleton_creature.png",
    reward: 10,
    hp: 150,
    attack: 50,
    attackType: "Magic",
    speed: 20,
    defense: 20,
    critical: 10,
  },
  {
    id: 2,
    name: "Skeleton",
    imgPath: "img/creature/skeleton_creature_spear.png",
    reward: 10,
    hp: 100,
    attack: 45,
    attackType: "Normal",
    speed: 20,
    defense: 15,
    critical: 50,
  },
  {
    id: 3,
    name: "Skeleton",
    imgPath: "img/creature/skeleton_creature_bow.png",
    reward: 10,
    hp: 100,
    attack: 25,
    attackType: "Normal",
    speed: 50,
    defense: 15,
    critical: 50,
  },
];

export const enemyCreatureLobby1 = [
  {
    id: 1,
    name: "Dragon",
    imgPath: "img/creature/dragon_creature.png",
    reward: 80,
    hp: 1000,
    attack: 50,
    attackType: "Normal",
    speed: 30,
    defense: 20,
    critical: 25,
  },
];
