const relics = [
  {
    id: 1,
    name: "Gust of Hermes",
    description: "Grants the user's summon +5 speed while relic is being used. (Infinite duration.)",
    imgPath: "img/relic/relic1.webp",
    effectClass: "relic_effect1",
    hpMod: 0,
    attackMod: 0,
    speedMod: 5,
    defenseMod: 0,
    criticalMod: 0,
    mpMod: 0,
    mpRegenMod: 0,
    specialMod: 0,
    price: 0,
  },
  {
    id: 2,
    name: "Spark of Zeus",
    description: "Grants the user's summon +15 attack while relic is being used. (Infinite duration.)",
    imgPath: "img/relic/relic2.webp",
    effectClass: "relic_effect2",
    hpMod: 0,
    attackMod: 15,
    speedMod: 0,
    defenseMod: 0,
    criticalMod: 0,
    mpMod: 0,
    mpRegenMod: 0,
    specialMod: 0,
    price: 500,
  },
  {
    id: 3,
    name: "Cup of Dionysus",
    description: "Grants the user's summon +25 MP regen while relic is being used. (Infinite duration.)",
    imgPath: "img/relic/relic3.webp",
    effectClass: "relic_effect3",
    hpMod: 0,
    attackMod: 0,
    speedMod: 0,
    defenseMod: 0,
    criticalMod: 0,
    mpMod: 0,
    mpRegenMod: 20,
    specialMod: 0,
    price: 500,
  }
];

export default relics;